name: Run CSGO Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes

jobs:
  run-oddeven:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run script
        run: python oddeven.py
